spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  devtools:
    livereload:
      enabled: true
  security:
    user:
      name: hyewonj
      password: hyewonj

logging:
  level:
    root: debug

#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: src/main/resources/bootsecurity.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: bootsecurity